### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by tschoonj** [rosalindfranklininstitute/alabdac#10]
@GMW99 there appears to be a security warning regarding your pillow version in requirements.txt. Could you address this please?

Also, my personal position is that constraints should be avoided: if the latest release of a dependency cannot be used, then I consider that to be a bug. 😄

**Comment by LAShemilt** [comment]
The versions are frozen for this particular project because it was part of a Masters project that had a set amount of time, and could not always be continuosly developed to adapt to dependencies. Once the masters is submitted and this becomes a continuously developed project we will updated everything to the latest version.
